name: GitHub Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        name: GitHub Webhook Handler ${{ github.ref_name }}
        body: TODO
        draft: true
        prerelease: false
